### ISSUE TITLE
Operational status Diplomat

### ISSUE THREAD

**Issue by Senna318** [klejejs/python-thermia-online-api#15]
Hi, I Believe I have a similar issue as this one;  #14 

I have a Thermia Diplomat. The statuses  do not show properly. In the Thermia Online can see the operational statuses. 
![image](https://user-images.githubusercontent.com/10389096/212564660-099f5223-df0a-4328-b120-a821570a1466.png)

But this is the output from the example.py:

`
Operational status
Operational status: None
Available operational statuses: None
Available operational statuses map: None
Auxiliary heater 3KW: 1
Auxiliary heater 6KW: 2
Auxiliary heater 9KW: None
Auxiliary heater 12KW: None
Auxiliary heater 15KW: None
Compressor status: 1
Brine pump status: 2
Radiator pump status: None
Cooling status: 8
Hot water status: 16
Heating status: 32
Integral: -150
Pid: None
`

I have done a few runs with different statuses being active.  The debug files are the same each time. The only relevant difference I find is 
- Nothing Running: COMP_STATUS Value 4
- Brinepump and Hot water Running: COMP_STATUS Value 22
- Compressor and Brinepump and Heating Running COMP_STATUS Value 39

[debug compressor brinepump and heating active.txt](https://github.com/klejejs/python-thermia-online-api/files/10421120/debug.compressor.brinepump.and.heating.active.txt)
[debugnothing active.txt](https://github.com/klejejs/python-thermia-online-api/files/10421121/debugnothing.active.txt)
[debug brinepump and hotwater running.txt](https://github.com/klejejs/python-thermia-online-api/files/10421122/debug.brinepump.and.hotwater.running.txt)

**Comment by klejejs** [comment]
Thanks for reporting! The latest release `3.12` includes the fix.
Please let me know if there are still any issues.
