### ISSUE TITLE
Error setting register

### ISSUE THREAD

**Issue by Tobti** [klejejs/python-thermia-online-api#18]
HI!

Thanks for a great job!

I have been using your api for more then 1 year and so far hade no problem, and if any, i just updated to the latest, and it just worked.

But this time i start to have a problem yesterday and then i updated to the latest version, but i sill have the same problem.
I get this error message where ## is the register number i try to set. 

"Error setting register ## value. 400"

The Thermia app still works good. I tried to create a new account and tried an other computer and on an other site. Still the same problem. Any suggestions?

**Comment by Gjorret** [comment]
Im suddently getting the same issue.

`python.exe : Error setting register 33617 value. 400`

It started happening 22 marts.

**Comment by Tobti** [comment]
I have Ver 3.13 and still a problem.
The updated to 3.13 solved the issue of setting the wanted temperature, but the rest of the registers are not possible to set so example registers 51 & 63. I'm usings the classic interface, if this is of any help.

Thanks in advance!

**Comment by Tobti** [comment]
I Changed from "RegisterIndex" to "RegisterId" in Heatpump.py line 289 and TermiaAPI line 236.

Now it works for me :)

**Comment by Core242** [comment]
I'm using the Genenis interface and unfortunately your fix didnt help me Tobti. However changing line 301 in ThermiaAPI 
from "registerindex": switch_data["RegisterIndex"] 
to "registerindex": switch_data["RegisterId"] 
gave me the posibilitiy to change the switches again.  Thanx for the hint anyway.

**Comment by klejejs** [comment]
Thanks for the suggestions!
There were further Thermia API changes. Please check if there are still issues and reopen the issue if problems persist.
