### ISSUE TITLE
Problem with hotwater switch

### ISSUE THREAD

**Issue by Core242** [klejejs/python-thermia-online-api#19]
Hi, first of all thanks for a great API. unfortunately the hotwater switch stopped working with the latest update giving me "Error setting register 1059 value. 400". I have included my Debug test if you have a chance to take a look.
All the best
/J
[debug.txt](https://github.com/klejejs/python-thermia-online-api/files/11071628/debug.txt)

**Comment by Gjorret** [comment]
This was fixed in the latest release.

**Comment by klejejs** [comment]
There were further Thermia API changes. Please check if there are still issues and reopen the issue if problems persist.
