### ISSUE TITLE
 Can not set parameters

### ISSUE THREAD

**Issue by Vovanoso** [klejejs/python-thermia-online-api#20]
When example.py runs using  CHANGE_HEAT_PUMP_DATA_DURING_TEST =True it gaves:
Error setting register 6010 value. 400
Error setting register 52 value. 400
Error setting register 51 value. 400

**Comment by klejejs** [comment]
Hello! It looks like Thermia themselves had issues last week. Could you please try again and see if it works now? If not, could you please attach the debug.txt file?

**Comment by Vovanoso** [comment]
Sending debug.txt
[debug.txt](https://github.com/klejejs/python-thermia-online-api/files/11448985/debug.txt)

**Comment by klejejs** [comment]
@Vovanoso is this still an issue you are concerned with?

**Comment by Vovanoso** [comment]
Dear KrisjanisI checked. Now it works normally.Many thanks. Best regardsVictor Ganetsky 16 окт. 2023 г., в 00:12, Krisjanis Lejejs ***@***.***> написал(а):﻿
@Vovanoso is this still an issue you are concerned with?
