### ISSUE TITLE
Genesis went down?

### ISSUE THREAD

**Issue by Gjorret** [klejejs/python-thermia-online-api#24]
I know its not an issue with the script, but anyone can confirm they also having issue getting data out?

Last time i was able to fetch was 4am UTC+2.

Seems like its actually able to get temperatures but getting 404 on fetching devices (maybe a bit random if it succeeds or not)

[online-genesis](https://www.online-genesis.thermia.se/) is blank, so i guess there is an issue (i was wondering if i got blocked or so, but also happens from work).

Anyways, have you seen that its possible to get COP on the device now with new firmware. Do you know if its possible to get that out from the API? (Currently online viewable on the device).

Thanks for a great piece of software!

Regards,
Rasmus

**Comment by flexi80** [comment]
Yes, I've got problem, can't login via website or app either.

**Comment by klejejs** [comment]
Seems like it is working again. Unfortunately, there is nothing we can do about what happens to the Thermia cloud but kudos for starting a discussion. 👌🏻
