### ISSUE TITLE
State ”Unknown”

### ISSUE THREAD

**Issue by cmragnar** [klejejs/python-thermia-online-api#34]
State says ”Unknown” – should be “No demand” or others.

Operations I can switch in Thermia Online desktop (or app).
Temperature
Hotwater (on/off)
Boost (on/off)
Room Senor (On/Off)

Operational Status in thermia online:
Manual
Hot water
Heating
Active cooling
Pool
Anti Legionella
Passive cooling
StandBy
No Demand
Off

Debug file:
[debug.txt](https://github.com/user-attachments/files/15884761/debug.txt)

![image](https://github.com/klejejs/python-thermia-online-api/assets/52965048/3ed1f0fd-0f4a-4c1a-a176-4de66803fd74)
![image](https://github.com/klejejs/python-thermia-online-api/assets/52965048/ddf3130d-4e2c-40d4-966e-394a09204f6a)
![image](https://github.com/klejejs/python-thermia-online-api/assets/52965048/c4de37e0-3851-4a11-8ed0-c88df0151695)
![image](https://github.com/klejejs/python-thermia-online-api/assets/52965048/6de58117-a21e-4262-9379-84c5203b6181)

**Comment by klejejs** [comment]
Thanks for reporting the issue and for the debug file, it will help figuring out the problem.
Closing this issue, however, as it relates to Home Assistant, and can be tracked in https://github.com/klejejs/ha-thermia-heat-pump-integration/issues/73 and https://github.com/klejejs/ha-thermia-heat-pump-integration/issues/72
