### ISSUE TITLE
Feature: Add REG_HEATING_HEAT_CURVE

### ISSUE THREAD

**Issue by klejejs** [klejejs/python-thermia-online-api#4]
I received a message saying that get and set functions for REG_HEATING_HEAT_CURVE would also be useful for this API.

**Comment by Swifster** [comment]
Yes this would be an extremely useful function so it would be possible to build some kind of  electric stock compensation system. Lower heat curve when prize of energy is high and rise when low.

**Comment by klejejs** [comment]
The latest release includes generic functions to fetch all register groups, registers for the specific group, and data for specific registers. It also includes a setter function to set the value of a specific register.
These can now be used to get and set any register value with the API.
