### ISSUE TITLE
support for DHP-H Opti Pro+ models

### ISSUE THREAD

**Issue by wouterse** [klejejs/python-thermia-online-api#5]
I have a Danfoss DHP-H Opti Pro+ 10 heatpump (profile Diplomat / Diplomat duo); obviously not supported by the thermal-online-api. However I gave it a try, and many things work well:

* all data that was returned seems to be correct
* set_temperature works correctly
* set_operation_mode works correctly

However, it does not provide the current Operational Status. The test program (Danfoss.py) gives:

Operational status
Operational status: None
Available operational statuses: []
Available operational statuses map: {}

It would be great if the api would provide the operational status information. The information is available as the Thermia website shows:

Compressor Running
Brinepump Running
Active cooling -
Hot water -
Heating Running
Integral -29

I realise that I run the api in an unsupported environment so I was really pleased to see well this worked in its current state. It seems only a small step to get the api fully operational on the DHP-H models and I can definitely help in testing the api on my heatpump.

**Comment by klejejs** [comment]
Hello @wouterse. Sorry for the late reply.
I have added a `debug()` command to the `example.py` file, which will generate a `debug.txt` file so I can better understand your heat pump. Could you please send me that generated file?
