### ISSUE TITLE
Feature: Add REG_HOT_WATER_BOOST

### ISSUE THREAD

**Issue by msand83** [klejejs/python-thermia-online-api#7]
Would it be possible to have get and set functions for REG_HOT_WATER_BOOST for this API?

**Comment by klejejs** [comment]
Hello. Thanks for the request. I will look into adding this.

**Comment by wouterse** [comment]
With different heat pumps and different ways they are operated, people will want to have read/write access to different registers. I'd suggest to add a generic get and set interface where you supply a registerName and a groupName, and a value for the set-version.

**Comment by mmmahammm** [comment]
Agree it would be more useful to set different registers. For example, believe Diplomat optimum does not have water boost option. 

Instead, would be useful to get access to hot water minimum and maximum values, and hot water start temp. By doing this, it would be possible to automate/tweak/force heatpump to start hot water heating during low cost hours.

**Comment by randriksen** [comment]
it would be awesome to be able to set the boost

**Comment by klejejs** [comment]
@wouterse thanks for the suggestion about generic functions. The latest release includes them to fetch all register groups, registers for the specific group, and data for specific registers. It also includes a setter function to set the value of a specific register.
These can now be used to get and set any register value with the API.
Please see `README.md` and `example.py` for more info about them.
