### ISSUE TITLE
Operation mode for control of heating

### ISSUE THREAD

**Issue by Goran58** [klejejs/python-thermia-online-api#8]
Hi Krisjanis,
Thank you for a really great library. I intend to use your library to force the heating to the hours with the cheapest electricity. With your knowledge, which operation mode do you recommend to enable/disable the heating? I have a Thermia Calibra Eco.
Best Regards,
Goran

**Comment by klejejs** [comment]
Hello, I am not very familiar with all the heating modes Thermia offers for different heap pumps, so it is hard for me to recommend anything. With my heap pump, I would use HOT WATER operation mode to turn off heating, but leave water heating on and COMPRESSOR or AUX.HEATER mode to turn on heating depending on if I want to heat with electricity or not.
I hope this helps you, as I cannot offer any more suggestions :(

**Comment by Goran58** [comment]
Thank you for your suggestions.
